package com.fancy.cms.model;

public class ThesisWithBLOBs extends Thesis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesis.Content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesis.Message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thesis.Cremark
     *
     * @mbggenerated
     */
    private String cremark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesis.Content
     *
     * @return the value of thesis.Content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesis.Content
     *
     * @param content the value for thesis.Content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesis.Message
     *
     * @return the value of thesis.Message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesis.Message
     *
     * @param message the value for thesis.Message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thesis.Cremark
     *
     * @return the value of thesis.Cremark
     *
     * @mbggenerated
     */
    public String getCremark() {
        return cremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thesis.Cremark
     *
     * @param cremark the value for thesis.Cremark
     *
     * @mbggenerated
     */
    public void setCremark(String cremark) {
        this.cremark = cremark == null ? null : cremark.trim();
    }
}